name: sam2_qt_env

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pip

  # PyQt5 화면 구성
  - pyqt=5

  # 이미지, 비디오, 마스크 처리
  - numpy>=1.24
  - opencv
  - pillow

  # 영상 처리 보조
  - ffmpeg

  # SAM2 / AI
  - pytorch>=2.3
  - torchvision>=0.18

  # 기타
  - tqdm
  - matplotlib

  - pip:
      - git+https://github.com/facebookresearch/segment-anything-2.git
