name: kitech_segmentation

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip

  # PyQt5
  - pyqt=5

  # image/video
  - numpy>=1.24
  - opencv
  - pillow
  - ffmpeg

  # CUDA PyTorch
  - pytorch>=2.3
  - torchvision>=0.18
  - pytorch-cuda=12.1

  # utils
  - tqdm
  - matplotlib

  - pip:
      - git+https://github.com/facebookresearch/segment-anything-2.git
      - qt-material

      # SAM3 / HuggingFace
      - transformers
      - huggingface_hub
      - accelerate
      - safetensors
